### ISSUE TITLE
Unsupported in Jellyfin 10.9.0+

### ISSUE THREAD

**Issue by osh123** [LizardByte/Themerr-jellyfin#310]
### Describe the Bug

Seems like Themerr is not working in Jellyfin 10.9.
Installed the latest version, but still, doesn't work.
![Screenshot 2024-05-13 at 10 45 05](https://github.com/LizardByte/Themerr-jellyfin/assets/1708736/fafe5e5f-d1a2-49b6-9331-5c8e6dfb9b78)

### Additional Context

Themerr version: 2024.511.1724.56
Jellyfin version: 10.9.1

**Comment by ReenigneArcher** [comment]
Unfortunately the Jellyfin plugins must be compiled for the target version as far as I understand.

I asked the Jellyfin developers if there was a migration guide, but didn't get much feedback... So this will take some time to investigate and release an updated version.

**Comment by Hadyark** [comment]
I'm currently trying to update the project but I have no knowledge of Jellyfin plugins.

I've reproduced what has been done in other plugins
https://github.com/Hadyark/Themerr-jellyfin/commit/3c92316431d52e68fa18f23693937c1afa9421ef

Except that when I try to build I get this error:

> .\Jellyfin.Plugin.Themerr\ThemerrManager.cs(24,35): error CS0246: The type or namespace name 'IServerEntryPoint' could not be found (are you missing a using directive or an assembly reference?) [.\Jellyfin.Plugin.Themerr\Jellyfin.Plugin.Themerr.csproj]

**Comment by ReenigneArcher** [comment]
`MediaBrowser.Controller.Plugin.IServerEntryPoint` doesn't exist in 10.9+. Unfortunately, the change is not going to be as simple as updating a few version numbers.

**Comment by Hadyark** [comment]
What's the reason why `ThemerrManager` implements `IServerEntryPoint `and not `BasePlugin<PluginConfiguration>` and `IHasWebPages` as done in the [template](https://github.com/jellyfin/jellyfin-plugin-template/blob/master/Jellyfin.Plugin.Template/Plugin.cs) and others plugins?

I see that in the [intro-skipper](https://github.com/jumoog/intro-skipper) plugin `IServerEntryPoint` has been replaced by `IHostedService` and `IDisposable` in this commit [https://github.com/jumoog/intro-skipper/commit/5d743302e41c88f0e8ac85cee88142ca1a235aee](url)

**Comment by ReenigneArcher** [comment]
`IServerEntryPoint` was used in the plugin that I was referencing when I created this plugin initially.
